# Generated by Django 2.2.6 on 2019-10-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('choice_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='webapp.Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='webapp.Poll', verbose_name='Ответ')),
            ],
        ),
    ]
