# Generated by Django 2.2.6 on 2019-10-19 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='webapp.Choice', verbose_name='Вариант Ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='webapp.Poll', verbose_name='Вопрос'),
        ),
    ]
